name: Discord Message Updater

on:
  push:
    branches:
      - main

jobs:
  update-discord-rules:
    runs-on: ubuntu-latest
    environment: Discord-Bot

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: python3 -m pip install -U discord.py

      - name: Run Discord updater
        run: python discord_updater.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          MESSAGE_ID: ${{ secrets.MESSAGE_ID }}